apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoestore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoestore-api
  template:
    metadata:
      labels:
        app: shoestore-api
    spec:
      containers:
        - name: shoestore-api
          image: your-image-name
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_HOME
              value: "/usr/lib/jvm/java-17-openjdk-amd64"
            - name: PATH
              value: "/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH"